### ISSUE TITLE
希望添加普通aidl方式的服务注册

### ISSUE THREAD

**Issue by Carlos2927** [HiWong/InterStellar#3]
看了作者的项目介绍，确实不错，不用编写aidl文件，像普通接口一样只有添加了aidl注解即可动态实现aidl。但是还是希望提供普通aidl方式注册服务支持，因为如果是跟其他第三方应用有通信交互时用的的还是静态的aidl方式

**Comment by Carlos2927** [comment]
你那个Andromeda我看了，但我比较喜欢这个，如果别人给我的是aidl文件，我是不是将它改成你这个项目所需的对应的服务接口再加上aidl注解就可以正常使用了？

**Comment by Carlos2927** [comment]
@HiWong

**Comment by HiWong** [comment]
哈哈，对的，其实就不用aidl了，相当于在普通接口的基础上加上注解就行了

**Comment by 70kg** [comment]
@HiWong 感觉这个项目和Andromeda差不多？除了不用写aidl还有什么区别吗，看你上面提到的知乎文章，好像也没有提到很多区别。似乎InterStellar 写起来更方便？

**Comment by HiWong** [comment]
对的，大的架构跟Andromeda差不多，这是我业余时间尝试的一个小项目，就是想试试不写AIDL, 而是像本地接口调用一样来进行IPC. 但是它也是有价值的，因为有太多的binder的话容易进程结束时容易出现SWT异常

**Comment by HiWong** [comment]
@70kg 你可以把它当作https://github.com/Xiaofei-it/Hermes 这个项目的一个完全体，这是我前同事的一个项目，当时这个项目不支持in, out, inout, oneway这些，对于数据类型的支持也不够，然后我就用另外一种方式实现了它。

**Comment by HiWong** [comment]
@70kg 是这样的，所以各有优劣
